endpoints y routes preeliminares
MarcoRooks/EnterpriseLogBackend pull request #6
Opened 2022-02-21 15:24 UTC by miguelCidPaz

Routes enlazados a controllers, no esta nada hecho solo enlazado para empezar a trabajarlo.
Mañana quedamos que se quita que se deja y vemos como abordar la conexion a la db.
Faltan los managers para manejar la conexion y los services para las acciones que queramos llamar dentro de la api.

2022-02-21 15:28 UTC, miguelCidPaz commented
Los dos conflictos que presenta es por los models con la encapsulacion, cuando vayamos a mergearlo se quita lo que venga de mi rama y se dejan los models que hay en des

2022-02-22 13:52 UTC, maestre7 reviewed
los campos de user.js y worker.js en models están en español, tendrían q estar en ingles si no me confundo. Antes de hacer un pullrequest acostúmbrate a mergear des en tu branch para evitar conflictos.

2022-02-22 14:19 UTC, maestre7 commented
si modificas eso aprovecha y añade un 201 a new user para cuando ya exista.

2022-02-22 19:05 UTC, MarcoRooks requested changes
Evitar este merge y autorizar el que hare

2022-02-22 19:05 UTC, merged